//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneToXClient.ListOfNumbers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ListOfNumbers.IWebServer")]
    public interface IWebServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServer/GetJsonArray", ReplyAction="http://tempuri.org/IWebServer/GetJsonArrayResponse")]
        int[] GetJsonArray(int input_number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServer/GetJsonArray", ReplyAction="http://tempuri.org/IWebServer/GetJsonArrayResponse")]
        System.Threading.Tasks.Task<int[]> GetJsonArrayAsync(int input_number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebServerChannel : OneToXClient.ListOfNumbers.IWebServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServerClient : System.ServiceModel.ClientBase<OneToXClient.ListOfNumbers.IWebServer>, OneToXClient.ListOfNumbers.IWebServer {
        
        public WebServerClient() {
        }
        
        public WebServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int[] GetJsonArray(int input_number) {
            return base.Channel.GetJsonArray(input_number);
        }
        
        public System.Threading.Tasks.Task<int[]> GetJsonArrayAsync(int input_number) {
            return base.Channel.GetJsonArrayAsync(input_number);
        }
    }
}
